# import de python
FROM python:3.9-slim

WORKDIR /app

# Pour supprimer les avertissements de root
ENV PIP_ROOT_USER_ACTION=ignore

COPY requirements.txt requirements.txt

# Pour eviter des erreur et avertissement
# RUN pip install --progress-bar off --upgrade pip

# RUN pip install -r requirements.txt
RUN pip install --progress-bar off -r requirements.txt

COPY . /app

# RUN ls

EXPOSE 8501

CMD ["streamlit", "run", "app/frontend.py"]
# RUN streamlit run app/frontend.py

# ENTRYPOINT ["streamlit", "run"]

# CMD ["app/frontend.py"]

