FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . . 

RUN ls


# EXPOSE 4000

CMD ["python", "./app/Pretraitement_modelisation/pretraitement_modelisation.py"]
