FROM python:3.9-slim AS development

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

RUN ls

EXPOSE 5000

ENTRYPOINT ["python"]

CMD ["app/backend.py"]


