FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . . 

RUN ls

RUN python collect.py

RUN python app/process/pretraitement_modelisation.py

EXPOSE 3000

# CMD ["python", "app/process/pretraitement_modelisation.py"]