version: '3.3'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile-web
      # target: development
    container_name: churn_finance_g2_web-app
      # image: churn_finance_g2_web-app
    volumes:
      - .:/app
    command: streamlit run app/frontend.py
    security_opt:
      - seccomp:unconfined
    depends_on:
      - backend
    ports:
      - 8501:8501

  backend:
    build:
      context: .
      dockerfile: Dockerfile-back
      # target: development
    volumes:
      - .:/app
    command: python app/backend.py
    security_opt:
      - seccomp:unconfined
    depends_on:
      - mysql
      # - postgres
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/churn_finance
      # DATABASE_URL: postgres://user:password@postgres:5432/churn_finance
      # NODE_ENV: development
      PORT: 5000
    ports:
        - 5000:5000


  mysql:
    image: mysql:latest
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: password
      MYSQL_DATABASE: churn_finance
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 20M
    ports:
    - 8899:80
    