# import de python
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

RUN ls

EXPOSE 8501

ENTRYPOINT [ "streamlit","run" ]

CMD ["app/frontend.py"]


