FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY ./app/collect ./app

RUN ls

RUN python ./app/collect.py

EXPOSE 4000

CMD ["python", "./app/collect.py"]