FROM python:3.9-slim

WORKDIR /app

# Pour supprimer les avertissements de root
ENV PIP_ROOT_USER_ACTION=ignore

COPY requirements.txt requirements.txt

RUN pip install --progress-bar off --upgrade pip

# RUN pip install -r requirements.txt
RUN pip install --progress-bar off -r requirements.txt

COPY . /app

# RUN ls

# RUN python app/backend.py

EXPOSE 5000

# CMD ["python", "app/backend.py", "--host", "0.0.0.0", "--port", "5000" , "--reload"]

CMD ["python", "app/backend.py"]

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" , "--reload"]

# ENTRYPOINT ["python"]

# CMD ["app/backend.py"]

